Add skull-trace to better tracing memory stat in realtime

diff --git a/scripts/bin/skull b/scripts/bin/skull
--- a/scripts/bin/skull
+++ b/scripts/bin/skull
@@ -22,6 +22,7 @@ function print_usage()
     echo " \_ skull build"
     echo " \_ skull deploy"
     echo " \_ skull start"
+    echo " \_ skull trace"
     echo " \_ skull version"
     echo " \_ skull help"
     echo ""
@@ -67,6 +68,7 @@ function prepare()
     . $SKULL_ROOT/lib/skull/skull_action_build.bash
     . $SKULL_ROOT/lib/skull/skull_action_deploy.bash
     . $SKULL_ROOT/lib/skull/skull_action_start.bash
+    . $SKULL_ROOT/lib/skull/skull_action_trace.bash
     . $SKULL_ROOT/lib/skull/skull_action_version.bash
     . $SKULL_ROOT/lib/skull/skull_action_config.bash
 
@@ -102,7 +104,7 @@ fi
 
 # 2. Process Commands
 case "$1" in
-    (create|version|start)
+    (create|version|start|trace)
         prepare false
         entry=$1
         shift
@@ -122,7 +124,7 @@ case "$1" in
     (help)
         shift
         if [ $# -eq 0 ]; then
-            echo "Error: need a command entry name. - eg: skull help module" >&2
+            echo "Error: Invalid command name. - eg: skull help 'command'" >&2
             exit 1
         fi
 
